export enum SettingGroups {
  CET_MRV = 'CET_MRV',
  CRU_MRV = 'CRU_MRV',
  GOO_MRV = 'GOO_MRV',
  REC_MRV = 'REC_MRV',
  COMMON_MRV = 'COMMON_MRV',
  CET_POLICY = 'Tymlez_CET',
  CRU_POLICY = 'Tymlez_CRU',
  GOO_POLICY = 'Tymlez_GOO',
  REC_POLICY = 'Tymlez_REC',
  System = 'System',
  Platform = 'Platform',
  TrustChain = 'TrustChain',
}

export enum SettingKeys {
  READING_METRIC_NAME = 'ReadingMetricName',
  READING_CONVERSION_RATE = 'ReadingConversionRate',
  CARBON_EMISSION_METRIC_NAME = 'CarbonEmissionMetricNames',
  CARBON_EQ_EMISSION_METRIC_NAME = 'CarbonEqEmissionMetricNames',
  CARBON_REDUSSION_METRIC_NAME = 'CarbonReductionMetricNames',
  OTHER_MRV_DATA_METRIC_NAME = 'OtherMRVDataMetricNames',
  CARBON_EMISSION_CONVERSION_RATE = 'CarbonEmissionConversionRate',
  CARBON_REDUCTION_CONVERSION_RATE = 'CarbonReductionConversionRate',
  GUARDIAN_TENANCY_NAME = 'GuardianTenancyName',
  TOKEN_MINT_VALUE = 'TokenMintValue',
  CH4_METRIC_NAME = 'Ch4EmissionMetricName',
  NO2_METRIC_NAME = 'NO2EmissionMetricName',
  SKIP_METER_ASSOCIATION = 'SkipMeterAssociation',
  SKIP_ZERO_MRV_SUBMISSION = 'SkipZeroMrvSubmission',
  SENSITIVE_FIELD_NAMES = 'SensitiveFieldNames',
  DOVU_LINK = 'DovuLink',
  TRUSTCHAIN_DEFAULT_ACCOUNT = 'TrustchainDefaultAccount',
  TRUSTCHAIN_ALL_ACCOUNTS = 'TrustchainAllAccounts',
  TRUSTCHAIN_ACTIVE_ACCOUNTS = 'TrustchainActiveAccounts',
  TRUSTCHAIN_DEFAULT_NETWORK = 'TrustchainDefaultNetwork',
  TRUSTCHAIN_DEFAULT_DECRYPTIONKEY = 'TrustchainDefaultDecryptionKey',
  GOO_AGGREGATION_FIELD = 'TymlezGooAggregationFields',
  CET_AGGREGATION_FIELD = 'TymlezCETAggregationFields',
  CRU_AGGREGATION_FIELD = 'TymlezCRUAggregationFields',
  REC_AGGREGATION_FIELD = 'TymlezRECAggregationFields',
  ENABLED_POLICY_TAGS = 'enabledPolicyTags',
  DEFAULT_OTHER_MRV_DATA = 'DefaultOtherMRVData',
}
