export enum PERMISSIONS {
  ALL_RESOURCE_WRITE = '*.write',
  ALL_RESOURCE_READ = '*.read',
  IDENTITY_MANAGEMENT_WRITE = 'identity_management.write',
  IDENTITY_MANAGEMENT_READ = 'identity_management.read',

  PLATFORM_CONFIG_WRITE = 'platform-config.write',
  PLATFORM_CONFIG_READ = 'platform-config.read',

  GUARDIAN_CONFIG_WRITE = 'guardian.write',
  GUARDIAN_CONFIG_READ = 'guardian.read',

  CLIENT_DASHBOARD_READ = 'client-dashboard.read',
  TRUSTCHAIN_READ = 'trustchain.read',

  AUDIT_REPORT_READ = 'audit-report.read',

  CLIENT_DATA_READ = 'data.read',
  MRV_MANUAL_UPLOAD = 'mrv.upload',
  MRV_MANUAL_APPROVE = 'mrv.approve',
  DOVU_READ = 'dovu.read',
}

export enum DEFAULT_ROLES {
  ADMIN = 'admin',
  CONFIG_ADMIN = 'config-admin',
  CLIENT = 'client',
  AUDITOR = 'auditor',
  DATA_OPERATOR = 'platform-data-operator',
}

export const DEFAULT_ROLE_PERMISSIONS = {
  [DEFAULT_ROLES.ADMIN]: [
    PERMISSIONS.ALL_RESOURCE_WRITE,
    PERMISSIONS.ALL_RESOURCE_READ,
    PERMISSIONS.TRUSTCHAIN_READ,
    PERMISSIONS.DOVU_READ,
    PERMISSIONS.CLIENT_DASHBOARD_READ,
  ],
  [DEFAULT_ROLES.CLIENT]: [
    PERMISSIONS.CLIENT_DASHBOARD_READ,
    PERMISSIONS.TRUSTCHAIN_READ,
    PERMISSIONS.DOVU_READ,
  ],
  [DEFAULT_ROLES.AUDITOR]: [
    PERMISSIONS.AUDIT_REPORT_READ,
    PERMISSIONS.TRUSTCHAIN_READ,
  ],
  [DEFAULT_ROLES.CONFIG_ADMIN]: [
    PERMISSIONS.PLATFORM_CONFIG_WRITE,
    PERMISSIONS.PLATFORM_CONFIG_READ,
  ],
  [DEFAULT_ROLES.DATA_OPERATOR]: [
    PERMISSIONS.PLATFORM_CONFIG_WRITE,
    PERMISSIONS.PLATFORM_CONFIG_READ,
  ],
};

const IDENTITY_PERMISSIONS = {
  READ: [PERMISSIONS.ALL_RESOURCE_READ, PERMISSIONS.IDENTITY_MANAGEMENT_READ],
  WRITE: [
    PERMISSIONS.ALL_RESOURCE_WRITE,
    PERMISSIONS.IDENTITY_MANAGEMENT_WRITE,
  ],
};

const CONFIG_PERMISSIONS = {
  READ: [PERMISSIONS.ALL_RESOURCE_READ, PERMISSIONS.PLATFORM_CONFIG_READ],
  WRITE: [PERMISSIONS.ALL_RESOURCE_WRITE, PERMISSIONS.PLATFORM_CONFIG_WRITE],
};

const GUARDIAN_PERMISSIONS = {
  READ: [PERMISSIONS.ALL_RESOURCE_READ, PERMISSIONS.GUARDIAN_CONFIG_READ],
  WRITE: [PERMISSIONS.ALL_RESOURCE_WRITE, PERMISSIONS.GUARDIAN_CONFIG_WRITE],
};

const DATA_PERMISSIONS = {
  READ: [PERMISSIONS.ALL_RESOURCE_READ, PERMISSIONS.MRV_MANUAL_UPLOAD],
  WRITE: [PERMISSIONS.ALL_RESOURCE_WRITE, PERMISSIONS.MRV_MANUAL_APPROVE],
};

const CLIENT_DASHBOARD_PERMISSIONS = [
  PERMISSIONS.CLIENT_DASHBOARD_READ,
  PERMISSIONS.ALL_RESOURCE_READ,
  PERMISSIONS.DOVU_READ,
];

const CLIENT_TRUSTCHAIN_PERMISSIONS = [
  PERMISSIONS.TRUSTCHAIN_READ,
  PERMISSIONS.ALL_RESOURCE_READ,
];

const AUDIT_PERMISSIONS = [
  PERMISSIONS.AUDIT_REPORT_READ,
  PERMISSIONS.ALL_RESOURCE_READ,
];

export const PERMISSION_SET = {
  //USER
  USER_MANAGEMENT: [
    ...IDENTITY_PERMISSIONS.READ,
    ...IDENTITY_PERMISSIONS.WRITE,
  ],
  USER_WRITE_MANAGEMENT: IDENTITY_PERMISSIONS.WRITE,
  USER_READ_MANAGEMENT: IDENTITY_PERMISSIONS.READ,

  //GUARDIAN
  GUARDIAN_MANAGEMENT: [
    ...GUARDIAN_PERMISSIONS.READ,
    ...GUARDIAN_PERMISSIONS.WRITE,
  ],
  GUARDIAN_WRITE_MANAGEMENT: GUARDIAN_PERMISSIONS.WRITE,
  GUARDIAN_READ_MANAGEMENT: GUARDIAN_PERMISSIONS.READ,

  //CONFIG
  CONFIG_MANAGEMENT: [...CONFIG_PERMISSIONS.READ, ...CONFIG_PERMISSIONS.WRITE],
  CONFIG_WRITE_MANAGEMENT: CONFIG_PERMISSIONS.WRITE,
  CONFIG_READ_MANAGEMENT: CONFIG_PERMISSIONS.READ,

  //DATA
  DATA_MANAGEMENT: [...DATA_PERMISSIONS.READ, ...DATA_PERMISSIONS.WRITE],
  DATA_WRITE_MANAGEMENT: DATA_PERMISSIONS.WRITE,
  DATA_READ_MANAGEMENT: DATA_PERMISSIONS.READ,

  //CLIENT
  CLIENT_DASHBOARD_ACCESS: CLIENT_DASHBOARD_PERMISSIONS,
  CLIENT_TRUSTCHAIN_ACCESS: CLIENT_TRUSTCHAIN_PERMISSIONS,
  AUDIT_ACCESS: AUDIT_PERMISSIONS,
};
